1. Giới thiệu pandas và cài đặt hiển thị

In [100]:
import numpy as np
import pandas as pd

In [101]:
from pandas import Series, DataFrame

In [102]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

#### 2. pandas Series – Mảng 1 chiều có nhãn (labeled array)
Thuộc tính quan trọng

obj.array → dữ liệu dạng numpy array

obj.index → đối tượng Index

obj.values → giá trị (tương tự .array)

In [103]:
obj = pd.Series([4, 7, -5, 3])  # Index tự động 0,1,2,3
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [104]:
obj.array
obj.index

RangeIndex(start=0, stop=4, step=1)

In [105]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

Truy cập dữ liệu

In [106]:
obj2["a"]  # Truy cập theo label
obj2["d"] = 6
obj2[["c", "a", "d"]]  # Fancy indexing

c    3
a   -5
d    6
dtype: int64

In [107]:
obj2[obj2 > 0]  # Boolean indexing
obj2 * 2   # Vectorized operations
import numpy as np
np.exp(obj2)   # Áp dụng hàm NumPy

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [108]:
"b" in obj2
"e" in obj2

False

Tạo Series từ dict

In [109]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)  # Key → index, value → data
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [110]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [111]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Xử lý missing data

In [112]:
pd.isna(obj4)
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [113]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [114]:
obj3
obj4
obj3 + obj4  # Tự động align theo index → NaN khi không khớp

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Đặt tên cho Series và index

In [115]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [116]:
obj
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

#### 3. pandas DataFrame – Bảng 2 chiều có nhãn

In [117]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [118]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [119]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [120]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Chỉ định thứ tự cột

In [121]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

Thêm cột mới không tồn tại → NaN

In [122]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Truy cập cột

In [123]:
frame2["state"]  # Trả về Series
frame2.year  # Dot notation (nếu tên cột hợp lệ)

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

Truy cập hàng

In [124]:
frame2.loc[1]  # Theo label index (dù index là số)
frame2.iloc[2]  # Theo vị trí (integer location)

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

Gán giá trị

In [125]:
frame2["debt"] = 16.5  # Gán giá trị cố định
frame2
frame2["debt"] = np.arange(6.) # Gán từ array
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [126]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
frame2["debt"] = val  # Gán từ Series (align theo index)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [127]:
frame2["eastern"] = frame2["state"] == "Ohio"  # Tạo cột boolean
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [128]:
del frame2["eastern"]  # Xóa cột
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

Tạo DataFrame từ nested dict

In [129]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [130]:
frame3 = pd.DataFrame(populations)  # Outer key → columns, inner key → index
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [131]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [132]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [133]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

Thuộc tính quan trọng

In [134]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [135]:
frame3.to_numpy()  # → numpy array 2D

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [136]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

#### 4. Index Objects trong pandas

In [137]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
index = obj.index
index
index[1:]

Index(['b', 'c'], dtype='object')

In [138]:
labels = pd.Index(np.arange(3))
labels
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2
obj2.index is labels

True

In [139]:
frame3
frame3.columns
"Ohio" in frame3.columns
2003 in frame3.index

False

In [140]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [141]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

#### 5. Reindexing – Sắp xếp lại index

In [142]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [143]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

Reindex DataFrame

In [144]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame
frame2 = frame.reindex(index=["a", "b", "c", "d"]) # Sắp lại hàng
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [145]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)  # Sắp lại cột

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [146]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [147]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

#### 6. Dropping (Xóa hàng/cột)

In [148]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj
new_obj = obj.drop("c")
new_obj
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [149]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Xóa trong DataFrame

In [150]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [151]:
data.drop(columns=["two"])  # Cách cũ

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [152]:
data.drop("two", axis=1)
data.drop(["two", "four"], axis="columns")  # Cách mới khuyến nghị

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

#### 7. Indexing, Selection, và Filtering

In [153]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj
obj["b"]
obj[1]
obj[2:4]
obj[["b", "a", "d"]]
obj[[1, 3]]
obj[obj < 2]

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\1027675808.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]
C:\Users\HP\AppData\Local\Temp\ipykernel_10824\1027675808.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

a    0.0
b    1.0
dtype: float64

In [154]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [155]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj1
obj2
obj1[[0, 1, 2]]
obj2[[0, 1, 2]]

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\2088379638.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [156]:
obj1.iloc[[0, 1, 2]]
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [157]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [158]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

DataFrame

In [159]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data
data["two"] # Cột → Series
data[["three", "one"]]  # Nhiều cột → DataFrame

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [160]:
data[:2]
data[data["three"] > 5]  # Boolean filtering

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [162]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [164]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [165]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [166]:
data.iloc[2]
data.iloc[[2, 1]]
data.iloc[2, [3, 0, 1]]
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [167]:
data.loc[:"Utah", "two"]
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [168]:
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
ser = pd.Series(np.arange(3.))
ser.iloc[-1]   # → 2.0

np.float64(2.0)

In [170]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [171]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\821879068.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]

np.float64(2.0)

In [172]:
ser.iloc[-1]

np.float64(2.0)

In [173]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [174]:
data.loc[:, "one"] = 1
data
data.iloc[2] = 5
data
data.loc[data["four"] > 5] = 3
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [175]:
data.loc[data.three == 5]["three"] = 6

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\867481848.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 5]["three"] = 6

In [176]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [177]:
data.loc[data.three == 5, "three"] = 6
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [178]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s1
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

#### 8. Phép toán giữa các đối tượng (Arithmetic & Alignment)

In [179]:
s1 + s2  # NaN khi index không khớp

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [180]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [181]:
df1 + df2  # NaN ở vị trí không giao nhau

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [182]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
df1
df2
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN

In [183]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, "b"] = np.nan
df1
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [184]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

Dùng phương thức với fill_value

In [185]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [186]:
1 / df1
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [187]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [188]:
arr = np.arange(12.).reshape((3, 4))
arr
arr[0]
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [189]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
frame
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [190]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [191]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Broadcasting (truyền theo hàng/cột)

In [192]:
series3 = frame["d"]
frame
series3
frame.sub(series3, axis="index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [193]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame)

               b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

Áp dụng hàm (apply / applymap / map)

In [194]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)  # Áp dụng theo cột (axis=0 mặc định)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [195]:
frame.apply(f1, axis="columns")  # Theo hàng

Utah      0.998382
Ohio      2.521511
Texas     0.676115
Oregon    2.542656
dtype: float64

In [196]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

            b         d         e
min -0.555730  0.281746 -1.296221
max  1.246435  1.965781  1.393406

In [197]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\2705683181.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

            b     d      e
Utah    -0.20  0.48  -0.52
Ohio    -0.56  1.97   1.39
Texas    0.09  0.28   0.77
Oregon   1.25  1.01  -1.30

In [198]:
frame["e"].map(my_format)

Utah      -0.52
Ohio       1.39
Texas      0.77
Oregon    -1.30
Name: e, dtype: object

#### 9. Sorting và Ranking

In [199]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [200]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame
frame.sort_index()
frame.sort_index(axis="columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [201]:
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

Sắp xếp theo giá trị

In [202]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [203]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [204]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [205]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [206]:
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

Ranking

In [207]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [208]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [209]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [210]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame
frame.rank(axis="columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [211]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

#### 10. Index trùng lặp (Duplicate Indexes)

In [212]:
obj.index.is_unique  # False nếu có trùng

False

In [213]:
obj["a"]  # Trả về Series nếu label trùng
obj["c"]

np.int64(4)

In [214]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])
df
df.loc["b"]  # Trả về DataFrame nếu index trùng
df.loc["c"]

0   -0.577087
1    0.124121
2    0.302614
Name: c, dtype: float64

In [215]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

11. Thống kê tóm tắt (Summarizing and Computing Descriptive Statistics)

In [216]:
df.sum()  # Theo cột

one    9.25
two   -5.80
dtype: float64

In [217]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [218]:
df.sum(axis="index", skipna=False)
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [219]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [220]:
df.idxmax()  # Index của giá trị lớn nhất

one    b
two    d
dtype: object

In [221]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [222]:
df.describe() # Tóm tắt số (count, mean, std, min, quartiles, max)

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [223]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()  # Với object → count, unique, top, freq

count     16
unique     3
top        a
freq       8
dtype: object

In [233]:
import yfinance as yf
import pandas as pd

tickers = ['AAPL', 'GOOG', 'IBM', 'MSFT']

# Tải dữ liệu một lần, dùng auto_adjust=True (mặc định) để Close đã điều chỉnh
data = yf.download(tickers, start='2010-01-01', end='2016-12-31', progress=False)

# Dùng 'Close' thay vì 'Adj Close' – vì nó đã là giá điều chỉnh!
price = data['Close']      # Đây chính là yahoo_price.pkl trong sách
volume = data['Volume']    # Tương tự yahoo_volume.pkl

# Xem thử
print("Price (Adjusted Close):")
print(price.head())

print("\nVolume:")
print(volume.head())

# Tính returns như trong sách
returns = price.pct_change()
print("\nReturns tail:")
print(returns.tail())

# Các ví dụ tiếp theo trong sách
print("\nCorrelation MSFT vs IBM:")
print(returns["MSFT"].corr(returns["IBM"]))

Price (Adjusted Close):
Ticker          AAPL       GOOG        IBM       MSFT
Date
2010-01-04  6.418384  15.494032  72.881493  23.130056
2010-01-05  6.429480  15.425802  72.001060  23.137529
2010-01-06  6.327210  15.036936  71.533356  22.995533
2010-01-07  6.315513  14.686884  71.285728  22.756384
2010-01-08  6.357501  14.882674  72.001060  22.913326

Volume:
Ticker           AAPL       GOOG      IBM      MSFT
Date
2010-01-04  493729600   78541293  6438444  38409100
2010-01-05  601904800  120638494  7156104  49749600
2010-01-06  552160000  159744526  5863144  58182400
2010-01-07  477131200  257533695  6109268  50559700
2010-01-08  447610800  189680313  4390271  51197400

Returns tail:
Ticker          AAPL      GOOG       IBM      MSFT
Date
2016-12-23  0.001978 -0.001706 -0.002095 -0.004878
2016-12-27  0.006351  0.002076  0.002579  0.000632
2016-12-28 -0.004264 -0.008212 -0.005684 -0.004583
2016-12-29 -0.000257 -0.002879  0.002467 -0.001429
2016-12-30 -0.007795 -0.014014 -0.003661 -0.012083

Correlation MSFT vs IBM:
0.4971182203629082

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\2453529898.py:7: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start='2010-01-01', end='2016-12-31', progress=False)

12. Correlation và Covariance

In [234]:
returns = price.pct_change()
returns.tail()

Ticker          AAPL      GOOG       IBM      MSFT
Date
2016-12-23  0.001978 -0.001706 -0.002095 -0.004878
2016-12-27  0.006351  0.002076  0.002579  0.000632
2016-12-28 -0.004264 -0.008212 -0.005684 -0.004583
2016-12-29 -0.000257 -0.002879  0.002467 -0.001429
2016-12-30 -0.007795 -0.014014 -0.003661 -0.012083

In [235]:
returns["MSFT"].corr(returns["IBM"])
returns["MSFT"].cov(returns["IBM"])

np.float64(8.730473860297962e-05)

In [236]:
returns.corr()                # Ma trận tương quan
returns.cov()                 # Ma trận hiệp phương sai

Ticker      AAPL      GOOG       IBM      MSFT
Ticker
AAPL    0.000272  0.000107  0.000076  0.000095
GOOG    0.000107  0.000248  0.000076  0.000108
IBM     0.000076  0.000076  0.000145  0.000087
MSFT    0.000095  0.000108  0.000087  0.000213

In [237]:
returns.corrwith(returns["IBM"])

Ticker
AAPL    0.384564
GOOG    0.402976
IBM     1.000000
MSFT    0.497118
dtype: float64

In [238]:
returns.corrwith(volume)  # So sánh với Series khác

Ticker
AAPL   -0.073304
GOOG   -0.007383
IBM    -0.201041
MSFT   -0.091856
dtype: float64

In [239]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

13. Unique values, value counts, membership

In [240]:
uniques = obj.unique()  # Giá trị duy nhất
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [241]:
obj.value_counts()  # Đếm tần suất (mặc định sắp xếp giảm dần)

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [242]:
pd.value_counts(obj.to_numpy(), sort=False)

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [243]:
obj
mask = obj.isin(["b", "c"])
mask
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

Mapping giá trị sang index số

In [244]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match) # → [0, 2, 1, 1, 0, 2] (c → 0, b → 1, a → 2)
indices

array([0, 2, 1, 1, 0, 2])

In [245]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [246]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

Value counts trên DataFrame

In [248]:
result = data.apply(pd.value_counts).fillna(0)  # Đếm tần suất từng giá trị theo cột
result

C:\Users\HP\AppData\Local\Temp\ipykernel_10824\4173609013.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)  # Đếm tần suất từng giá trị theo cột

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [249]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64

In [251]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS